### PR TITLE
Improve proving test coverage

### PR DESCRIPTION
**Pull request by eugenk**
This shall add missing tests and remove unused methods around proving.
Also, there are some minor refactorings (`alias_attribute`).

### CODE REVIEW

**Comment by tillmo** [comment]
Also for me, tests fail. E.g. I get
```
F
An error occurred in an after hook
  NoMethodError: undefined method `state=' for #<HetsInstance:0x000000121ab320>
  occurred at /home/till/.rvm/gems/ruby-2.1.7@ontohub/gems/activemodel-3.2.22/lib/active_model/attribute_methods.rb:407:in `method_missing'
```

**Comment by eugenk** [comment]
I don't know why, but it seems like the migrations have not completed in the `test` environment:
```
RAILS_ENV=test bundle exec rake db:migrate:reset
```

**Comment by tillmo** [comment]
oh, I think I forgot to migrate. Now I get (also for your command):
```
rake db:migrate:clean
[...]
==  RemoveUsedSentences: migrating ============================================
-- drop_table("used_sentences")
rake aborted!
StandardError: An error has occurred, this and all later migrations canceled:

PG::UndefinedTable: ERROR:  table "used_sentences" does not exist
: DROP TABLE "used_sentences"/home/till/.rvm/gems/ruby-2.1.7@ontohub/gems/rack-mini-profiler-0.9.7/lib/patches/db/pg.rb:90:in `exec'
/home/till/.rvm/gems/ruby-2.1.7@ontohub/gems/rack-mini-profiler-0.9.7/lib/patches/db/pg.rb:90:in `async_exec'
/home/till/.rvm/gems/ruby-2.1.7@ontohub/gems/activerecord-3.2.22/lib/active_record/connection_adapters/postgresql_adapter.rb:650:in `block in execute'
/home/till/.rvm/gems/ruby-2.1.7@ontohub/gems/activerecord-3.2.22/lib/active_record/connection_adapters/abstract_adapter.rb:280:in `block in log'
/home/till/.rvm/gems/ruby-2.1.7@ontohub/gems/activesupport-3.2.22/lib/active_support/notifications/instrumenter.rb:20:in `instrument'
/home/till/.rvm/gems/ruby-2.1.7@ontohub/gems/activerecord-3.2.22/lib/active_record/connection_adapters/abstract_adapter.rb:275:in `log'
/home/till/.rvm/gems/ruby-2.1.7@ontohub/gems/activerecord-3.2.22/lib/active_record/connection_adapters/postgresql_adapter.rb:649:in `execute'
/home/till/.rvm/gems/ruby-2.1.7@ontohub/gems/activerecord-3.2.22/lib/active_record/connection_adapters/abstract/schema_statements.rb:256:in `drop_table'
/home/till/.rvm/gems/ruby-2.1.7@ontohub/gems/foreigner-1.7.4/lib/foreigner/connection_adapters/sql2003.rb:13:in `drop_table'
/home/till/.rvm/gems/ruby-2.1.7@ontohub/gems/activerecord-3.2.22/lib/active_record/migration.rb:466:in `block in method_missing'
/home/till/.rvm/gems/ruby-2.1.7@ontohub/gems/activerecord-3.2.22/lib/active_record/migration.rb:438:in `block in say_with_time'
/home/till/.rvm/gems/ruby-2.1.7@ontohub/gems/activerecord-3.2.22/lib/active_record/migration.rb:438:in `say_with_time'
/home/till/.rvm/gems/ruby-2.1.7@ontohub/gems/activerecord-3.2.22/lib/active_record/migration.rb:458:in `method_missing'
/home/till/web2.0/ontohub/db/migrate/20151024152034_remove_used_sentences.rb:3:in `up'
```

**Comment by eugenk** [comment]
I rebased and amended the commit "Remove unused model: UsedSentence". This should be fixed now.

**Comment by tillmo** [comment]
now the tests go through.

**Comment by eugenk** [comment]
I rebased this on staging.

**Comment by tillmo** [comment]
Unfortunately, when again trying to rub the tests, I get a problem:
```
till@mark:~/web2.0/ontohub$ sudo service elasticsearch start
 * Starting Elasticsearch Server                                                 * Already running.                                                      [ OK ] 
till@mark:~/web2.0/ontohub$ rake
Elasticsearch is not running. Please start it before running the tests.
Aborting tests.
till@mark:~/web2.0/ontohub$ 
```

**Comment by tillmo** [comment]
my fault, invoker was not running...

**Comment by tillmo** [comment]
:+1:

**Pull request merged**
