### PR TITLE
1341 1447 handle proof statuses correctly

### LINKED ISSUE #1341: Adapt proof status according to axiom selection
This is a follow-up to #1135. If not all axioms have been selected, the proof status must be transformed before entering it into the database. Before implementing the issue, the transformation should be defined and theoretically justified. For example, NOC must be mapped to OPN, because we do not know whether the goal is a consequence of Ax just because it is not a consequence of some proper subset of Ax.

### PR DESCRIPTION
**Pull request by eugenk**
This shall fix #1341 and the first part of #1447. I dropped `NOC` because it looks like I made an implementation mistake in the first draft of the proof status handling. The global error page for `CONTR` theorems will be done later in another branch.

### CODE REVIEW

**Comment by tillmo** [comment]
when I try to prove the theorem of https://ontohub.org/sandbox/open_prop with this branch, I get a `processing` indefinitely.

**Comment by eugenk** [comment]
That's odd. I can't reproduce the `processing` locally. Is every invoker-handled process running (sidekiq, hets)? You can check it with
```
$  invoker list
  +-----+-------------+----------------------------+---------------------------------------------+
  | dir | pid         | process_name               | shell_command                               |
  +-----+-------------+----------------------------+---------------------------------------------+
  |     | 35223       | ontohub                    | bundle exec rails s                         |
  |     | 35224       | ontohub-sidekiq            | bundle exec sidekiq -q default -q hets -q.. |
  |     | 35225       | ontohub-hets               | bundle exec rake hets:run                   |
  |     | Not Running | ontohub-test-elasticsearch | TEST_CLUSTER_NODES=1 bundle exec rake ela.. |
  +-----+-------------+----------------------------+---------------------------------------------+
```
If elasticsearch is not running, this is no problem.

**Comment by tillmo** [comment]
I get
```
invoker list
  +-----+-------------+----------------------------+---------------------------------------------+
  | dir | pid         | process_name               | shell_command                               |
  +-----+-------------+----------------------------+---------------------------------------------+
  |     | 25630       | ontohub                    | bundle exec rails s                         |
  |     | 25632       | ontohub-sidekiq            | bundle exec sidekiq -q default -q hets -q.. |
  |     | 25635       | ontohub-hets               | bundle exec rake hets:run                   |
  |     | Not Running | ontohub-test-elasticsearch | TEST_CLUSTER_NODES=1 bundle exec rake ela.. |
  +-----+-------------+----------------------------+---------------------------------------------+
```

**Comment by eugenk** [comment]
Then I don't have a clue why this fails. Could you please reset the databases with
```
rake db:migrate:clean
redis-cli flushdb
```
then restart invoker and try again?

**Comment by tillmo** [comment]
I did this. When uploading any ontology, I now get
```
PG::UndefinedColumn: ERROR: column "provable" of relation "sentences" does not exist at character 151 : INSERT INTO "sentences" ("comments_count", "created_at", "display_text", "imported", "last_error", "locid", "name", "ontology_id", "proof_status_id", "provable", "range", "state", "state_updated_at", "text", "type", "updated_at") VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15, $16) RETURNING "id"
```

**Comment by tillmo** [comment]
I did this. When uploading any ontology, I now get
```
PG::UndefinedColumn: ERROR: column "provable" of relation "sentences" does not exist at character 151 : INSERT INTO "sentences" ("comments_count", "created_at", "display_text", "imported", "last_error", "locid", "name", "ontology_id", "proof_status_id", "provable", "range", "state", "state_updated_at", "text", "type", "updated_at") VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15, $16) RETURNING "id"
```

**Comment by eugenk** [comment]
Have you done it while being on this branch? `rake db:migrate:clean` and restarting invoker (actually sidekiq and the rails server) must be done on the brach you want to work with. Especially sidekiq has issues if you don't restart it after making changes (e.g. switching a branch).

**Comment by tillmo** [comment]
Oh yes, that was the problem. Now it works, thanks.

**Comment by tillmo** [comment]
:+1:

**Pull request merged**
