### PR TITLE
1439 parse the status attribute of theorems

### LINKED ISSUE #1439: Parse the status attribute of Theorems
According to https://github.com/spechub/Hets/issues/1509, Hets proves trivial Theorems during the static analysis. Adjust the parser to set the correct proof status from the beginning.

### PR DESCRIPTION
**Pull request by eugenk**
Shall fix #1439.

--

The branch of this pull request is **not based on staging**. Instead, it is based on the branch of #1440 (1438-add_support_for_tptp_evaluation). It might be easier to review that one first.

### CODE REVIEW

**Comment by tillmo** [comment]
I get the following problem:
```
till@mark:~/web2.0/ontohub$ rake db:migrate
Celluloid 0.17.0 is running in BACKPORTED mode. [ http://git.io/vJf3J ]
==  InitSchema: migrating =====================================================
-- create_table("alternative_iris", {:force=>true})
   -> 0.0494s
-- add_index("alternative_iris", ["ontology_id", "iri"], {:name=>"index_alternative_iris_on_ontology_id_and_iri", :unique=>true})
   -> 0.0076s
-- create_table("basic_proofs", {:force=>true})
rake aborted!
StandardError: An error has occurred, this and all later migrations canceled:

PG::InFailedSqlTransaction: ERROR:  current transaction is aborted, commands ignored until end of transaction block
:           SELECT tablename
          FROM pg_tables
          WHERE schemaname = ANY (current_schemas(false))
/home/till/.rvm/gems/ruby-2.1.5@ontohub/gems/activerecord-3.2.22/lib/active_record/connection_adapters/postgresql_adapter.rb:642:in `async_exec'
[...]
```

**Comment by eugenk** [comment]
Please use `rake db:migrate:clean`. This looks like a problem caused by switching from a branch that already has the new squashed migrations to one that doesn't (like this one).

**Comment by tillmo** [comment]
:+1:

**Comment by eugenk** [comment]
I added the commit fd4112a for a greater Hets version. Symbols in TPTP are present now.

**Pull request merged**
