### PR TITLE
1371 print better readable settings validation errors

### LINKED ISSUE #1371: Print better readable settings validation errors
As a follow-up on #1370, the settings validation errors need to be improved. They need to be better understandable.

### PR DESCRIPTION
**Pull request by eugenk**
This shall fix #1371. After some settings alterations the output looks something like:

```
❯ RAILS_ENV=production rails c
Rails Error: Unable to access log file. Please ensure that /Users/eugen/Work/Ontohub/ontohub/log/production.log exists and is chmod 0666. The log level has been raised to WARN and the output directed to STDERR until the problem is fixed.
Creating scope :state. Overwriting existing method Repository.state.
Creating scope :accessible_by. Overwriting existing method Repository.accessible_by.
The settings are invalid. Please check your config/settings[.local].yml or config/settings/production[.local].yml
The following errors were detected:

Please check the paths keys in the settings - data_root:
  is not a directory
  Value: /tmp/abc/data
Please check the paths keys in the settings - git_home:
  is not a directory
  Value: /git
Please check the paths keys in the settings - git_root:
  is not a directory
  Value: /tmp/abc/data/repositories
Please check the paths keys in the settings - symlink_path:
  is not a directory
  Value: /tmp/abc/data/git_daemon
Please check the paths keys in the settings - commits_path:
  is not a directory
  Value: /tmp/abc/data/commits
email:
  email adress must belong to the fully qualified domain name 'ontohub.org'.
  Value: noreply@example.com
allow_unconfirmed_access_for_days:
  must be greater than or equal to 0
  Value: -3
max_read_filesize:
  must be greater than 1024
  Value: -524288
max_combined_diff_size:
  must be greater than 2048
  Value: -1048576
Please set a valid value in the config/environments/production[.local].rb for log_level:
  is not included in the list (see the comments in the config/settings.yml at this key)
  Value: hans
hets.executable_path:
  must be an executable file: /usr/bin/hets
  Value: /usr/bin/hets

Stopping the application.
```

Note that I run rails in production environment to enable **all** the validations.

### CODE REVIEW

**Comment by 0robustus1** [comment]
Are sure that these are correct default values? 

```
max_read_filesize:
  must be greater than 1024
  Value: -524288
max_combined_diff_size:
  must be greater than 2048
  Value: -1048576
```

**Comment by eugenk** [comment]
Those are not the defaults. I made some settings alterations to provoke invalid values ;)

**Comment by 0robustus1** [comment]
Could you iterate the steps you took to test the validation messages?

**Comment by eugenk** [comment]
I altered the `config/settings.yml` (could have created a `config/settings.local.yml` as well, but altering the `settings.yml` is quicker) and changed some values according to the output I put in the starting post.

Next, I started rails with `RAILS_ENV=production rails s`. That's all.

The production mode is needed because *some* of the validations are only processed in the production mode (e.g. if directories exist).

**Comment by 0robustus1** [comment]
Sorry i still can't reproduce any of that. All i get is this:

```
RAILS_ENV=production bundle exec rails s                                                                                                      @uni/ontospace/ontohub
=> Booting WEBrick
=> Rails 3.2.21 application starting in production on http://0.0.0.0:3000
=> Call with -d to detach
=> Ctrl-C to shutdown server
Exiting
/usr/local/var/rbenv/versions/2.1/gemsets/global/gems/activesupport-3.2.21/lib/active_support/dependencies.rb:251:in `require': cannot load such file -- exception_notification/rails (LoadError)
```

**Comment by eugenk** [comment]
I just tried this again and I seem to have forgotten something. The ` database.yml` needs to be adjusted, too, at the production key to try this on the development machines. I created a gist for the `database.yml` and for the local settings files to reproduce this: https://gist.github.com/eugenk/67934341962e1052d6d3

I can't explain, though, why you get an error with the bundle. Doesn't `RAILS_ENV=production bundle install` help?

**Comment by 0robustus1** [comment]
Already did that, no. I also tried `bundle install --deployment`.

**Comment by eugenk** [comment]
That's very odd. I deployed this to develop.ontohub.org. It's not a good workaround, but you could change some settings on that machine and try to start the rails console to see the error messages.

**Comment by 0robustus1** [comment]
The default for `git_home` is `~/git` which is expanded during `config/initializers/paths.rb`, which will return a stack-trace error if the `git` user doesn't exist.
We should move the `paths.rb`-content into a new module SettingsInterpretation, which will be performed after settings-validation.

**Comment by eugenk** [comment]
I added 5 small commits. This should be done now.

**Comment by eugenk** [comment]
Now the tests should be green again

**Comment by eugenk** [comment]
I just rebased on staging (after merging #1392). Hopefully Travis is green now.

**Comment by ebolloff** [comment]
:+1:  don't know if @0robustus1 wants to review it, too?

**Comment by 0robustus1** [comment]
:+1:

**Pull request merged**
