### PR TITLE
Specify GIT_HOME environment variable for rebuild script

### PR DESCRIPTION
**Pull request by eugenk**
The GIT_HOME environment variable was not set in the rebuild script.
This adds a default value.

### CODE REVIEW

**Comment by ebolloff** [comment]
There are some things which are broken on my machine right now, thats why I got a red test (which is also red on other branches). Maybe @SGraef wants to check it, too? On my side :+1:

**Comment by eugenk** [comment]
I added another fix because the first commit didn't really use the absolute file path.

**Comment by 0robustus1** [comment]
Just a question from my side: Why do we need a specific Environment Variable to be set (mandatory)? Usually those are only used to provide options and it should work with reasonable defaults without specifiying an Env-Var.

**Comment by eugenk** [comment]
There's no place in the ontohub code/settings files any more where we have this path. I could've hard coded the default default directly into the rake task. I didn't do so because many rake tasks have mandatory environment variable settings and I didn't want production systems to have a default.

**Comment by 0robustus1** [comment]
Alright. Even though you have already documented the variable in the productive-deployment documentation i would suggest to also document it in development related documentation, just so we can easily know about it in a few months/years time.

**Comment by eugenk** [comment]
Right. Done with d492d49

**Comment by SGraef** [comment]
:+1:

**Pull request merged**
