### PR TITLE
1134 reduce the axiom set with logic independent sine

### LINKED ISSUE #1134: Reduce the axiom set with logic independent SInE
Krystof Hoder and Andrei Voronkov presented SInE, a heuristic to reduce the set of axioms used for proving a theorem, in their paper [Sine Qua Non for Large Theory Reasoning](http://202.154.59.182/mfile/files/Information%20System/Automated%20Deduction%3B%2023rd%20International%20Conference,%20CADE%202011/Chapter%2023%20Sine%20Qua%20Non%20for%20Large%20Theory%20Reasoning.pdf).

The method is also described briefly in their [slides](http://resources.mpi-inf.mpg.de/departments/rg1/conferences/deduction10/slides/krystof-hoder.pdf).

Implement it logic-independently. Use ontohub's information on the symbols and sentences to select the sentences which the provers shall use.

### PR DESCRIPTION
**Pull request by eugenk**
This shall fix #1134.

--

~~The branch of this pull request is **not based on staging** but on the following branches:~~
~~* 1411-restructure_proving_pipeline (#1427)~~
~~* 1134-create_basis_for_many_axiom_selection_methods (#1391)~~

~~The first commit if this branch is:~~
~~bb7d8c6 Add skeleton of SineAxiomSelection.~~

### CODE REVIEW

**Comment by eugenk** [comment]
I rebased this on staging.

**Comment by eugenk** [comment]
I rebased on staging and added two commits for the specs:

f2ff50b Add SInE parameter tests.
34a32f8 Use subject syntax all over the spec file.

**Comment by eugenk** [comment]
I suggest to review #1440 and #1441 first. Those add a very convenient mutex. In this branch, we need a mutex and we use the ConcurrencyBalancer for it. This makes it overly complicated, though. I would like to replace it by rebase as soon as #1441 is merged.

**Comment by tillmo** [comment]
I just tried this branch and have one quick comment for now: in the "SInE Axiom Selection", the three numerical values to be selected should be better explained (perhaps with tooltips? or at least in the wiki). Moreover, the input fields could be smaller.
Will now turn to #1444.

**Comment by eugenk** [comment]
I cherry-picked the important commit from #1444 (Add redis semaphore.) and amended the next commit here to get the functionality right. This is ready for review now. 

I will add hints to the form and some information to the wiki about the SInE parameters.

**Comment by tillmo** [comment]
Please add some documentation about Sine, e.g. a reference to the Vonkorov paper, or later also a reference to your thesis.

**Comment by tillmo** [comment]
:+1:

**Pull request merged**
