### PR TITLE
Remove spec for removed cleanup method.

### PR DESCRIPTION
**Pull request by eugenk**
This takes care of a leftover of #1522. I seem to have forgotten to remove the `cleanup` specs.

### CODE REVIEW

**Comment by tillmo** [comment]
strange that the tests passed for #1522

**Comment by eugenk** [comment]
Indeed. Maybe not all tests are run in travis, again.

**Comment by tillmo** [comment]
but now they are, because the tests are red...

**Comment by tillmo** [comment]
:+1:

**Pull request merged**
