### PR TITLE
1396 settings set paths implicitly

### LINKED ISSUE #1396: Settings: set paths implicitly
All settings keys except for `data` beneath `paths` should be set implicitly if they are nil. For example,
```yml
paths:
  data: data
  git_repositories: # nil
  symlinks: # nil
  commits: # nil
  git_home: # nil
```
should be interpreted as
```yml
paths:
  data: data
  git_repositories: data/repositories
  symlinks: data/git_daemon
  commits: data/commits
  git_home: data/git
```

### PR DESCRIPTION
**Pull request by eugenk**
This shall fix #1396.

I needed to remove the previous settings validations for the respective keys and add a custom validator class to allow nil values.

--

~~The branch of this pull request is based on **1371-print_better_readable_settings_validation_errors** (#1372)  instead of **staging**. It might be easier to review that one first.~~

~~The first new commit in this branch is~~
~~b2551b5 Add default paths constant to PathsInitializer.~~

### CODE REVIEW

**Comment by eugenk** [comment]
I just rebased this on staging.

**Comment by eugenk** [comment]
Don't trust travis and jenkins here. See #1404.

**Comment by eugenk** [comment]
Rebased again on staging. The tests fail now if the settings validations fail.

**Comment by eugenk** [comment]
jenkins, test this please.

**Comment by eugenk** [comment]
jenkins, test this please

**Comment by SGraef** [comment]
:+1:

**Pull request merged**
