### PR TITLE
1467 send file name extension as input type to hets

### LINKED ISSUE #1467: send file name extension as input type to Hets

### PR DESCRIPTION
**Pull request by eugenk**
This shall fix #1467.

### CODE REVIEW

**Comment by eugenk** [comment]
jenkins, test this please

**Comment by eugenk** [comment]
jenkins, test this please

**Comment by eugenk** [comment]
We need to wait for https://github.com/spechub/Hets/issues/1529

**Comment by eugenk** [comment]
jenkins, test this please

**Comment by eugenk** [comment]
I rebased this on staging

**Comment by eugenk** [comment]
The tests fail because #1543 is not merged yet.

**Comment by eugenk** [comment]
This can be reviewed now.

**Comment by eugenk** [comment]
I rebased this on staging

**Comment by SGraef** [comment]
:+1:  looks fine for me

**Pull request merged**
