### PR TITLE
1233 json for model resources

### LINKED ISSUE #1233: Implement JSON-structures for model-resources in Status Code 200
We should implement JSON-structures for model-resources in the case of a *200*/*OK* response.
The list of currently planned model-resources is this one:

- [x] Logic
- [x] Repository
- [x] Ontology
- [x] OntologyVersion
- [x] OntologyMember::Symbol
- [x] Sentence
- [x] Mapping
- [x] LicenseModel
- [x] FormalityLevel

### PR DESCRIPTION
**Pull request by 0robustus1**
Shall close #1233. I did also throw in serialization for ontology type as an additional gimmick. Project and Task will probably follow in a later issue/PR.

Ah one additional note, this Pull Request is based on the **1166-add_mimetype_info_to_controllers** branch instead of **staging**. So one might want to review (and merge) #1240 before tackling this pr.

### CODE REVIEW

**Comment by eugenk** [comment]
:+1:

**Comment by eugenk** [comment]
Wait, no thumbs up right now. Reviewing #1248, I found that subdirectories have "weird" json output (I assume that's because `GitRepository::Files::GitFile` has no seralizer):
```
❯ curl -H 'Accept: application/json' http://ontohub.dev/default/a_subdirectory
[#<GitRepository::Files::GitFile:0x007fc115489c10 @path="a_subdirectory/.gitkeep", @repository=#<GitRepository:0x007fc11548a9f8 @repo=#<Rugged::Repository:70233631249620 {path: "/Users/eugen/Work/Ontohub/ontohub/data/repositories/2/"}>>, @rugged_object=#<Rugged::Blob:0x007fc115489508 @owner=#<Rugged::Repository:70233631249620 {path: "/Users/eugen/Work/Ontohub/ontohub/data/repositories/2/"}>>, @oid="774cce832dde4eb4bc33989762272a970b8fa64f", @name=".gitkeep", @mime_type=#<Mime::Type:0x007fc109c29288 @synonyms=[], @symbol=:text, @string="text/plain">, @mime_category="text">, #<GitRepository::Files::GitFile:0x007fc115489080 @path="a_subdirectory/Px.clif", @repository=#<GitRepository:0x007fc11548a9f8 @repo=#<Rugged::Repository:70233631249620 {path: "/Users/eugen/Work/Ontohub/ontohub/data/repositories/2/"}>>, @rugged_object=#<Rugged::Blob:0x007fc1154889c8 @owner=#<Rugged::Repository:70233631249620 {path: "/Users/eugen/Work/Ontohub/ontohub/data/repositories/2/"}>>, @oid="774cce832dde4eb4bc33989762272a970b8fa64f", @name="Px.clif", @mime_type=#<Mime::Type:0x007fc109c29288 @synonyms=[], @symbol=:text, @string="text/plain">, @mime_category="text">, #<GitRepository::Files::GitFile:0x007fc115488568 @path="a_subdirectory/cat.clif", @repository=#<GitRepository:0x007fc11548a9f8 @repo=#<Rugged::Repository:70233631249620 {path: "/Users/eugen/Work/Ontohub/ontohub/data/repositories/2/"}>>, @rugged_object=#<Rugged::Blob:0x007fc115573e28 @owner=#<Rugged::Repository:70233631249620 {path: "/Users/eugen/Work/Ontohub/ontohub/data/repositories/2/"}>>, @oid="774cce832dde4eb4bc33989762272a970b8fa64f", @name="cat.clif", @mime_type=#<Mime::Type:0x007fc109c29288 @synonyms=[], @symbol=:text, @string="text/plain">, @mime_category="text">]
```

**Comment by 0robustus1** [comment]
Does it say anywhere that this issue is supposed to support json-output for subdirectories? (or other files). I don't belive that is part of this pull-request ;)

**Comment by eugenk** [comment]
Alright. Then :+1:

**Pull request merged**
