### PR TITLE
1134 create basis for many axiom selection methods

### PR DESCRIPTION
**Pull request by eugenk**
This prepares for #1134. It allows to have many different AxiomSelection methods, each with different parameters. As of this pull request, we only have the (previously available) ManualAxiomSelection which the user can directly select axioms with.

In the next step (next pull request based on this branch) I will add SInE as an automatic axiom selection.

### CODE REVIEW

**Comment by eugenk** [comment]
I just rebased on staging (after merging #1392). Hopefully Travis is green now.

**Comment by tillmo** [comment]
Hm, after a `rake db:migrate:clean`, I get for `rake db:seed`:
```
rake db:seed
Celluloid 0.17.0 is running in BACKPORTED mode. [ http://git.io/vJf3J ]
001-hets.rb
002-clean_git.rb
010-users_and_teams.rb
020-logicgraph.rb
Writing file: LogicGraph.xml
030-proof_statuses.rb
040-git.rb
041-proving.rb
rake aborted!
ActiveRecord::StatementInvalid: PG::NotNullViolation: ERROR:  null value in column "axiom_selection_id" violates not-null constraint
DETAIL:  Failing row contains (1, null, 6, null, null, 2015-07-12 13:08:33.123, 2015-07-12 13:08:33.123, 1, /default/partial_order//v__T//proof-attempt-configuration-1, null).
: INSERT INTO "proof_attempt_configurations" ("axiom_selection_id", "created_at", "locid", "logic_mapping_id", "number", "ontology_id", "prover_id", "timeout", "updated_at") VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9) RETURNING "id"
/home/till/.rvm/gems/ruby-2.1.5@ontohub/gems/activerecord-3.2.22/lib/active_record/connection_adapters/postgresql_adapter.rb:1176:in `get_last_result'
[...]
```

**Comment by eugenk** [comment]
> Hm, after a rake db:migrate:clean, I get for rake db:seed

Oh, yes. I forgot to adjust the seeds to the new parameter.

**Comment by eugenk** [comment]
The seeds should be fixed with 9b931be.

**Comment by tillmo** [comment]
Thanks, seeds work now.

**Comment by tillmo** [comment]
:+1:

**Comment by eugenk** [comment]
I decided to add a unique index on the association: 890ac4d

**Pull request merged**
