### PR TITLE
635 backup script

### LINKED ISSUE #635: backup
Back up the database and the repositories regularly. (I think that currently only the whole VM is backed up.)

### PR DESCRIPTION
**Pull request by eugenk**
Shall fix #635. Tested successfully on develop. Sudo access is required.

### CODE REVIEW

**Comment by ebolloff** [comment]
Some kind of note, where you can find the doku (https://github.com/ontohub/ontohub/blob/staging/doc/backup_and_restore_of_ontohub_data.md), in the script would be nice

**Comment by ebolloff** [comment]
I created a backup on develop `/home/ontohub/ontohub_data_backup/2015-05-28_11-40-42` but the `ontohub_sql_dump.postgresql` is empty.

**Comment by eugenk** [comment]
develop.ontohub.org is currently not responding, so I secure-copied the script to staging.ontohub.org and ran the backup as the ontohub user. It seems to work just fine:
```
ontohub@ontohub-staging:~$ mkdir ontohub_data_backup
ontohub@ontohub-staging:~$ /srv/http/ontohub/current/script/backup create
Creating backup...
Enabling maintenance mode...
FileUtils.touch /srv/http/ontohub/shared/data/maintenance.txt
FileUtils.mkdir_p /home/ontohub/ontohub_data_backup/2015-06-03_11-48-15
Creating SQL dump...
[executing next command in /home/ontohub/ontohub_data_backup/2015-06-03_11-48-15]
pg_dump -Fc ontohub > ontohub_sql_dump.postgresql
Creating repository archive...
[executing next command in /srv/http/ontohub/shared]
tar -v -czf /home/ontohub/ontohub_data_backup/2015-06-03_11-48-15/ontohub_repositories.tar.gz data/repositories data/git_daemon
Disabling maintenance mode...
FileUtils.rm /srv/http/ontohub/shared/data/maintenance.txt
Created backup in /home/ontohub/ontohub_data_backup/2015-06-03_11-48-15
ontohub@ontohub-staging:~$ cd ontohub_data_backup/2015-06-03_11-48-15/
ontohub@ontohub-staging:~/ontohub_data_backup/2015-06-03_11-48-15$ ll
insgesamt 10332
drwxr-xr-x 2 ontohub ontohub    4096 Jun  3 11:48 ./
drwxr-xr-x 3 ontohub ontohub    4096 Jun  3 11:48 ../
-rw-r--r-- 1 ontohub ontohub 7429822 Jun  3 11:48 ontohub_repositories.tar.gz
-rw-r--r-- 1 ontohub ontohub 3137860 Jun  3 11:48 ontohub_sql_dump.postgresql
```

I don't want to try out the restore functionality on staging without testing it on develop once again.

**Comment by eugenk** [comment]
Jenkins, test this please. (This comment will be removed as soon as the job is scheduled)

**Comment by ebolloff** [comment]
When I run the script on develop, `htop` shows that `tar` doesn't do anything.

**Comment by eugenk** [comment]
To do: Check if the `maintenance.txt` exists. Handle the problem.

**Comment by eugenk** [comment]
The `-z` in the `tar` command is not necessary. It can be omitted.

**Comment by eugenk** [comment]
Now all the comments should be worked off. Please check the new commits and try again to backup/restore.

**Comment by eugenk** [comment]
I just rebased on staging (after merging #1392). Hopefully Travis is green now.

**Comment by ebolloff** [comment]
As `ontohub` user, I don't have permission to create a backup on `develop`

**Comment by eugenk** [comment]
Now the last issues should be solved. Restoring the git repositories while preserving file permissions doesn't work because we can't run `sudo` as `ontohub`.

**Comment by ebolloff** [comment]
On `develop` as a ontohub user
```
bash-4.3$ ./backup create
/usr/bin/env: ruby: No such file or directory
```

**Comment by tillmo** [comment]
user admin can call the backup script (without the part for git repos) as user ontohub, and only use root rights for restoring git repos.
Alternatively, admin could `source ~ontohub/.profile`, but this way is not the preferred one.

**Comment by eugenk** [comment]
Now, backups need to be created as root user with
```
+ su - -c '~ontohub/webapp/script/backup create'
```

**Comment by eugenk** [comment]
This still needs some changes in the printed output, but it is mostly done and it is already working on the production machines. I use it every day on te.

**Comment by ebolloff** [comment]
Please update the wiki.

**Comment by eugenk** [comment]
The wiki is updated and the code is cleaned now.

**Comment by ebolloff** [comment]
:+1:

**Pull request merged**
