### PR TITLE
1443 fix evaluation state on theorems

### LINKED ISSUE #1443: Fix evaluation state on theorems
The evaluation state (pending, processing, done, failed) on Theorem is not updated properly.

### PR DESCRIPTION
**Pull request by eugenk**
This shall fix #1443.

### CODE REVIEW

**Comment by tillmo** [comment]
:+1:

**Comment by tillmo** [comment]
If there are multiple proof attempts, their statuses should be combined by taking maximum in the following total order: failed - no_result - pending - processing - fetching - done, where no_result is a new status that should be set in case of a timeout.

**Comment by eugenk** [comment]
I added the state selection based on the total order in bb0972f.

**Comment by tillmo** [comment]
I get an error when running the tests:
```
rake db:migrate:clean
[...]
rake db:seed
[...]
rake
[...]
/home/till/.rvm/gems/ruby-2.1.5@ontohub/gems/activerecord-3.2.22/lib/active_record/connection_adapters/postgresql_adapter.rb:1163:in `async_exec': PG::UndefinedTable: ERROR:  relation "axiom_selections" does not exist (ActiveRecord::StatementInvalid)
LINE 5:              WHERE a.attrelid = '"axiom_selections"'::regcla...
                                        ^
:             SELECT a.attname, format_type(a.atttypid, a.atttypmod),
                     pg_get_expr(d.adbin, d.adrelid), a.attnotnull, a.atttypid, a.atttypmod
              FROM pg_attribute a LEFT JOIN pg_attrdef d
                ON a.attrelid = d.adrelid AND a.attnum = d.adnum
             WHERE a.attrelid = '"axiom_selections"'::regclass
               AND a.attnum > 0 AND NOT a.attisdropped
             ORDER BY a.attnum
	from /home/till/.rvm/gems/ruby-2.1.5@ontohub/gems/activerecord-3.2.22/lib/active_record/connection_adapters/postgresql_adapter.rb:1163:in `exec_no_cache'
```

**Comment by eugenk** [comment]
Please try `RAILS_ENV=test rake db:migrate:reset`. I occasionally get the same error, but don't know where it comes from. Resetting the test database always fixes it.

**Comment by tillmo** [comment]
:+1:

**Pull request merged**
