### PR TITLE
1490 files in public are not accessible

### LINKED ISSUE #1490: Files in public directory are not accessible
If, for example, we try to access https://ontohub.org/robots.txt, rails doesn't find a route for this URL.
I think this happens because the `*path` route at the end of the routes.rb calls the IRIRouterConstraint which doesn't find an IRI.

### PR DESCRIPTION
**Pull request by SGraef**
should fix #1490

### CODE REVIEW

**Comment by eugenk** [comment]
jenkins, test this please

**Comment by eugenk** [comment]
jenkins, test this please

**Comment by eugenk** [comment]
Apart from my previous comment/change:
:+1:

**Comment by SGraef** [comment]
:+1:

**Pull request merged**
