### PR TITLE
1438 add support for tptp evaluation

### LINKED ISSUE #1438: Add support for TPTP evaluation
In order to evaluate axiom selection algorithms with large libraries, e.g. the [MPTP2078](http://wiki.mizar.org/twiki/bin/view/Mizar/MpTP2078), we need to parse TPTP files.

### PR DESCRIPTION
**Pull request by eugenk**
Shall fix #1438.

### CODE REVIEW

**Comment by tillmo** [comment]
When I upload a TPTP file, the axioms are displayed correctly, but there are no symbols. Probably this is a Hets problem?

**Comment by eugenk** [comment]
Yes, it's a Hets problem. Good catch

**Comment by eugenk** [comment]
I created https://github.com/spechub/Hets/issues/1510 for this.

**Comment by tillmo** [comment]
:+1:

**Pull request merged**
