### PR TITLE
Add puma_worker_killer gem

### PR DESCRIPTION
**Pull request by phyrog**
Adds the [puma worker killer](https://github.com/schneems/puma_worker_killer) gem to keep memory usage low.

Should be tested on develop before merging.

### CODE REVIEW

**Comment by phyrog** [comment]
This is deployed on develop now. The best way to check if it's working is probably to use develop and check after some hours/days if the memory usage has increased significantly. By default the workers are restarted on a rolling basis every 6 hours.

**Comment by ebolloff** [comment]
I clicked some large ontologies on `develop`. Currently the memory is about 8GB. I will check later, if the killer worked properly.

**Comment by phyrog** [comment]
The failure is unrelated to this PR, but I created a new issue for it (#1736).

**Comment by ebolloff** [comment]
:+1:

**Pull request merged**
