### PR TITLE
1318 create hets prove fixtures for different configurations

### LINKED ISSUE #1287: Parse SZS status from prover output
Use the prover output to get the SZS status of a proof attempt.

### LINKED ISSUE #1318: Create hets `prove` fixtures for different configurations
Currently we can only create hets fixtures for default proving options. We need tests for custom options like provers, axiom lists, goal lists, logic mappings etc.

### PR DESCRIPTION
**Pull request by eugenk**
Not only shall this fix #1318 but also close #1287.

This branch adds 
* tools for generating fixtures for the whole evaluation pipeline 
* tests for the SZS status evaluation which were missing in #1319.

The branch of this pull request is based on:
* 1287-parse_szs_status_from_prover_output (#1319)

The first new commit in this pull request is:
Fix MethodMissing in cucumber features.	88c40ed

### CODE REVIEW

**Comment by eugenk** [comment]
jenkins, test this please

**Comment by eugenk** [comment]
jenkins, test this please

**Comment by tillmo** [comment]
:+1:

**Comment by 0robustus1** [comment]
please rebase staging.

**Comment by eugenk** [comment]
I rebased on staging/1287-parse_szs_status_from_prover_output.

**Comment by eugenk** [comment]
I added two commits: 
61afd0c Adjust to snake_case keys.
c081725 Remove MathServe from prover output generator.

They should fix the red tests. Please review.

**Comment by tillmo** [comment]
:+1:

**Pull request merged**
