### PR TITLE
Lots of deployment fixes

### LINKED ISSUE #1414: Put cp_keys to data/.ssh/cp_keys
Apparently the `cp_keys` executable is not accessible at `${paths.git_home}/.ssh/cp_keys`, so put it to `${paths.data}/.ssh/cp_keys`

### LINKED ISSUE #1415: Implicit path settings fail
When the paths settings are nil/set implicitly *and* the directories actually exist, the validations fail.

### PR DESCRIPTION
**Pull request by eugenk**
This shall
* fix #1414
* fix #1415
* print a more useful error message if the cp_keys executable is missing. Previously, this printed a bad key and a bad value (only a good error message itself)

### CODE REVIEW

**Comment by SGraef** [comment]
:+1: looks fine to me

**Comment by eugenk** [comment]
Wow, you're fast :o

**Comment by tillmo** [comment]
does this mean that @jelmd can now have another try?

**Comment by eugenk** [comment]
Yes, that would be great. As soon as the next deployment attempt is made, I will investigate #1395 further.

**Pull request merged**
