### PR TITLE
Fix: Bundle is not complete for deployment

### LINKED ISSUE #1366: Bundle is not complete for deployment
VCR is used in the rake tasks, but it is only in the `test` group of the Gemfile. As soon as the rake tasks are loaded during deployment we get an error.

### PR DESCRIPTION
**Pull request by eugenk**
Shall fix #1366.

### CODE REVIEW

**Comment by eugenk** [comment]
I cherry-picked this commit to develop.ontohub.org (with conflict solving) and it works there.

**Comment by 0robustus1** [comment]
Could we document this somewhere? (What files/fixtures are used and why)

**Comment by eugenk** [comment]
You mean to extend [doc/most_important_gems.md](https://github.com/ontohub/ontohub/blob/20c5bf7fe7a97c1f44fef88424cfd8619735feb7/doc/most_important_gems.md)?

**Comment by 0robustus1** [comment]
That would be the place to add vcr and webmock, but i also want to document (maybe in productive deployment documentation, why we need the files and what they are used for, and when they are subject to change).

**Comment by eugenk** [comment]
Done with cb99870

**Comment by 0robustus1** [comment]
After green tests: :+1:

**Pull request merged**
