### PR TITLE
Update Ruby to from 2.1.10 to 2.2.5

### PR DESCRIPTION
**Pull request by ebolloff**
Ruby `> 2.1.10` forces you to add `test-unit` to your Gemfile, although we only use `rspec` and `cucumber`.  I tried to deactive it with (`application.rb`)
```
require 'rails'
require 'active_record/railtie'
require 'action_controller/railtie'
require 'action_mailer/railtie'
require 'active_resource/railtie'
# require 'rails/test_unit/railtie'
require 'sprockets/railtie'
```
The tests are green but and the end of it annoys you with 
```
invalid option: --profile
Test::Unit automatic runner.
```
and the manual of `test-unit`

### CODE REVIEW

**Comment by ebolloff** [comment]
jenkins, test this please

**Comment by ebolloff** [comment]
:+1:

**Comment by eugenk** [comment]
I suggest to directly upgrade to 2.2.5 which is a bugfix release from 2016-04-26.

**Comment by ebolloff** [comment]
jenkins, test this please

**Comment by eugenk** [comment]
:+1:

**Pull request merged**
